package wizard

import (
	"fmt"
	"os"
	"strings"

	tea "github.com/charmbracelet/bubbletea"
)

type WizardState int

const (
	StateStart WizardState = iota
	StateCreating
	StateCreateSucceeded
	StateCreateFailed
)

type wizardModel struct {
	state WizardState
}

func initialModel() wizardModel {
	return wizardModel{
		state: StateStart,
	}
}

func (m wizardModel) Init() tea.Cmd {
	return nil
}

// commands
type fileCreationResultMsg struct {
	err error
}

func writeDefaultInit() tea.Msg {
	configPath := "lockplane.toml"
	if _, err := os.Stat(configPath); err == nil {
		return fileCreationResultMsg{err: fmt.Errorf("file lockplane.toml already exists")}
	}
	var b strings.Builder
	b.WriteString("# Generated by: lockplane init\n")
	b.WriteString("#\n")
	b.WriteString("[environments.test]")
	b.WriteString("DATABASE_URL=...etc...")
	err := os.WriteFile(configPath, []byte(b.String()), 0600)
	return fileCreationResultMsg{err: err}
}

// update
func (m wizardModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {
		case "enter":
			return m.handleEnter()
		default:
			return m, tea.Quit
		}
	case fileCreationResultMsg:
		switch msg.err {
		case nil:
			m.state = StateCreateSucceeded
		default:
			m.state = StateCreateFailed
		}
		return m, tea.Quit
	}
	return m, nil
}

func (m wizardModel) handleEnter() (tea.Model, tea.Cmd) {
	switch m.state {
	case StateStart:
		return m, writeDefaultInit
		// return m, tea.Batch(writeDefaultInit, waitBeforeQuitting)
	}
	return m, nil
}

// render
func getResult(m wizardModel) string {
	switch m.state {
	case StateCreateFailed:
		return "Could not create the file"
	case StateCreateSucceeded:
		return "File created"
	default:
		return ""
	}
}

func (m wizardModel) View() string {
	switch m.state {
	case StateStart:
		return "Press Enter to create a lockplane.toml in this directory."
	case StateCreating:
		return "⏳ Creating file lockplane.toml"
	default:
		return getResult(m)
	}
}

func Run() error {
	p := tea.NewProgram(initialModel())
	m, err := p.Run()
	if err != nil {
		return err
	}
	if wm, ok := m.(wizardModel); ok {
		res := getResult((wm))
		if res != "" {
			_, err = fmt.Println(getResult(wm))
			return err
		}
		return nil
	} else {
		return fmt.Errorf("unexpected model type")
	}
}
